services:
  db:
    image: postgres:16
    env_file:
      -  .env
    volumes:
      -  postgres_data:/var/lib/postgresql/data
      -  ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  app:
    build:  ./app
    develop:
      watch:
        -  action: rebuild
           path: ./app
    ports:
      -  "8000:8000"
    env_file:
      -  .env
    depends_on:
      -  db
    restart: unless-stopped

volumes:
  postgres_data: 
